# Generated by Django 5.1.5 on 2025-02-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failedlogins', '0002_alter_failedlogin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedlogin',
            name='provided_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
