# Generated by Django 5.1.5 on 2025-03-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_directory_user_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('PLAINTEXT', 'Plaintext note'), ('MARKDOWN', 'Markdown note'), ('TODO', 'Todo list')], default='PLAINTEXT', max_length=255),
        ),
    ]
