# Generated by Django 5.1.5 on 2025-03-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
    ]
